// AUTO-GENERATED by scripts/scan-themes.js — do not edit manually

export interface ThemeMeta {
  name: string
  description: string
  author: string
}

export const themeManifest: Record<string, ThemeMeta> = {
  'default': {
    name: '기본 테마',
    description: '기본 라이트/다크 테마',
    author: 'kagla',
  },
  'ocean-blue': {
    name: '오션 블루',
    description: '파란색 계열 테마',
    author: 'kagla',
  }
}
