// AUTO-GENERATED by scripts/scan-themes.js — do not edit manually

export interface ThemeMeta {
  name: string
  description: string
  author: string
}

export const themeManifest: Record<string, ThemeMeta> = {
  'default': {
    name: 'Default theme',
    description: 'Default light/dark theme',
    author: 'kagla',
  },
  'ocean-blue': {
    name: 'Ocean Blue',
    description: 'Blue-toned theme',
    author: 'kagla',
  }
}
