// AUTO-GENERATED by scripts/scan-themes.js — do not edit manually

export interface ThemeMeta {
  name: string
  description: string
  author: string
}

export const themeManifest: Record<string, ThemeMeta> = {
  'cool-blue': {
    name: '쿨 블루',
    description: '깔끔한 블루 계열 테마 — 눈이 편하고 프로페셔널한 느낌',
    author: 'nexibase',
  },
  'default': {
    name: 'Default theme',
    description: 'Default light/dark theme',
    author: 'kagla',
  },
  'ocean-blue': {
    name: 'Ocean Blue',
    description: 'Blue-toned theme',
    author: 'kagla',
  }
}
