// AUTO-GENERATED by scripts/scan-plugins.js — do not edit manually
import dynamic from 'next/dynamic'

export interface WidgetDefinition {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  component: React.ComponentType<{ settings?: Record<string, any> }>
  label: string
  description: string
  defaultZone: 'hero' | 'main' | 'sidebar' | 'bottom'
  defaultColSpan: number
  defaultRowSpan: number
  settingsSchema: Record<string, unknown> | null
}

const CommunityGuide = dynamic(() => import('@/widgets/CommunityGuide'), { ssr: false })
const SiteStats = dynamic(() => import('@/widgets/SiteStats'), { ssr: false })
const WelcomeBanner = dynamic(() => import('@/widgets/WelcomeBanner'), { ssr: false })
const auction_AuctionLive = dynamic(() => import('@/plugins/auction/widgets/AuctionLive'), { ssr: false })
const boards_BoardCards = dynamic(() => import('@/plugins/boards/widgets/BoardCards'), { ssr: false })
const boards_LatestPosts = dynamic(() => import('@/plugins/boards/widgets/LatestPosts'), { ssr: false })
const boards_PopularBoards = dynamic(() => import('@/plugins/boards/widgets/PopularBoards'), { ssr: false })
const shop_ShopShortcut = dynamic(() => import('@/plugins/shop/widgets/ShopShortcut'), { ssr: false })

export const widgetRegistry: Record<string, WidgetDefinition> = {
  'community-guide': {
    component: CommunityGuide,
    label: '커뮤니티 가이드',
    description: '커뮤니티 이용 가이드',
    defaultZone: 'sidebar',
    defaultColSpan: 1,
    defaultRowSpan: 1,
    settingsSchema: null,
  },
  'site-stats': {
    component: SiteStats,
    label: '사이트 통계',
    description: '회원, 게시글, 댓글, 게시판 통계 카드',
    defaultZone: 'hero',
    defaultColSpan: 2,
    defaultRowSpan: 1,
    settingsSchema: null,
  },
  'welcome-banner': {
    component: WelcomeBanner,
    label: '환영 배너',
    description: '로그인 사용자 환영 메시지와 CTA 버튼',
    defaultZone: 'hero',
    defaultColSpan: 2,
    defaultRowSpan: 2,
    settingsSchema: null,
  },
  'auction-auction-live': {
    component: auction_AuctionLive,
    label: '진행중 경매',
    description: '',
    defaultZone: 'main',
    defaultColSpan: 2,
    defaultRowSpan: 1,
    settingsSchema: { limit: 4 },
  },
  'boards-board-cards': {
    component: boards_BoardCards,
    label: '게시판 카드',
    description: '',
    defaultZone: 'bottom',
    defaultColSpan: 4,
    defaultRowSpan: 1,
    settingsSchema: { limit: 4 },
  },
  'boards-latest-posts': {
    component: boards_LatestPosts,
    label: '최근 게시글',
    description: '',
    defaultZone: 'main',
    defaultColSpan: 2,
    defaultRowSpan: 2,
    settingsSchema: { limit: 6 },
  },
  'boards-popular-boards': {
    component: boards_PopularBoards,
    label: '인기 게시판',
    description: '',
    defaultZone: 'sidebar',
    defaultColSpan: 1,
    defaultRowSpan: 2,
    settingsSchema: { limit: 5 },
  },
  'shop-shop-shortcut': {
    component: shop_ShopShortcut,
    label: '쇼핑몰 바로가기',
    description: '',
    defaultZone: 'main',
    defaultColSpan: 1,
    defaultRowSpan: 1,
    settingsSchema: null,
  },
}
