const fs = require('fs')
const path = require('path')

const THEMES_DIR = path.join(__dirname, '..', 'src', 'themes')
const OUTPUT_FILE = path.join(THEMES_DIR, '_generated.ts')
const PUBLIC_THEMES_DIR = path.join(__dirname, '..', 'public', 'themes')

function scanThemes() {
  if (!fs.existsSync(THEMES_DIR)) {
    fs.mkdirSync(THEMES_DIR, { recursive: true })
  }

  // Ensure public/themes exists
  if (!fs.existsSync(PUBLIC_THEMES_DIR)) {
    fs.mkdirSync(PUBLIC_THEMES_DIR, { recursive: true })
  }

  const entries = fs.readdirSync(THEMES_DIR, { withFileTypes: true })
  const folders = entries
    .filter(e => e.isDirectory() && !e.name.startsWith('_'))
    .map(e => e.name)

  const themes = []

  for (const folder of folders) {
    const themeFile = path.join(THEMES_DIR, folder, 'theme.css')
    if (!fs.existsSync(themeFile)) {
      console.warn(`[scan-themes] Warning: ${folder}/ has no theme.css, skipping`)
      continue
    }

    // Check for optional meta
    let name = folder
    let description = ''
    let author = ''
    const metaFile = path.join(THEMES_DIR, folder, 'theme.meta.ts')
    if (fs.existsSync(metaFile)) {
      const content = fs.readFileSync(metaFile, 'utf-8')
      const getValue = (key) => {
        const match = content.match(new RegExp(`${key}:\\s*['"]([^'"]+)['"]`))
        return match ? match[1] : ''
      }
      name = getValue('name') || folder
      description = getValue('description') || ''
      author = getValue('author') || ''
    }

    themes.push({ folder, name, description, author })

    // Copy theme.css to public/themes/
    const dest = path.join(PUBLIC_THEMES_DIR, `${folder}.css`)
    fs.copyFileSync(themeFile, dest)
  }

  // Validate default exists
  if (!themes.find(t => t.folder === 'default')) {
    console.warn('[scan-themes] Warning: no default theme found')
  }

  // Generate manifest
  const entries2 = themes.map(t => `  '${t.folder}': {
    name: '${t.name}',
    description: '${t.description}',
    author: '${t.author}',
  }`)

  const output = `// AUTO-GENERATED by scripts/scan-themes.js — do not edit manually

export interface ThemeMeta {
  name: string
  description: string
  author: string
}

export const themeManifest: Record<string, ThemeMeta> = {
${entries2.join(',\n')}
}
`

  fs.writeFileSync(OUTPUT_FILE, output, 'utf-8')
  console.log(`[scan-themes] Found ${themes.length} theme(s): ${themes.map(t => t.folder).join(', ')}`)
}

scanThemes()
