const fs = require('fs')
const path = require('path')

const LAYOUTS_DIR = path.join(__dirname, '..', 'src', 'layouts')
const OUTPUT_FILE = path.join(LAYOUTS_DIR, '_generated.ts')
const COMPONENT_NAMES = ['Header', 'HomePage', 'Footer']

function scanLayouts() {
  // Ensure layouts dir exists
  if (!fs.existsSync(LAYOUTS_DIR)) {
    fs.mkdirSync(LAYOUTS_DIR, { recursive: true })
  }

  // Read subdirectories, skip _ prefixed
  const entries = fs.readdirSync(LAYOUTS_DIR, { withFileTypes: true })
  const folders = entries
    .filter(e => e.isDirectory() && !e.name.startsWith('_'))
    .map(e => e.name)

  // Validate default folder exists
  if (!folders.includes('default')) {
    console.error('ERROR: src/layouts/default/ folder is required but missing!')
    process.exit(1)
  }

  // Check default has all 3 files
  for (const comp of COMPONENT_NAMES) {
    const filePath = path.join(LAYOUTS_DIR, 'default', `${comp}.tsx`)
    if (!fs.existsSync(filePath)) {
      console.error(`ERROR: src/layouts/default/${comp}.tsx is required but missing!`)
      process.exit(1)
    }
  }

  // Build manifest
  const manifest = {}
  for (const folder of folders) {
    const files = {}
    for (const comp of COMPONENT_NAMES) {
      files[comp] = fs.existsSync(path.join(LAYOUTS_DIR, folder, `${comp}.tsx`))
    }
    manifest[folder] = { name: folder, files }
  }

  // Build dynamic import map entries
  const importEntries = []
  for (const folder of folders) {
    for (const comp of COMPONENT_NAMES) {
      if (manifest[folder].files[comp]) {
        importEntries.push(`  '${folder}/${comp}': dynamic(() => import('@/layouts/${folder}/${comp}'))`)
      }
    }
  }

  // Generate manifest file (server-safe, no dynamic)
  const manifestOutput = `// AUTO-GENERATED by scripts/scan-layouts.js — do not edit manually

export const layoutManifest = ${JSON.stringify(manifest, null, 2)} as const

export type LayoutFolder = keyof typeof layoutManifest
export type LayoutComponent = 'Header' | 'HomePage' | 'Footer'
`

  fs.writeFileSync(OUTPUT_FILE, manifestOutput, 'utf-8')

  // Generate component map file (client-only, uses dynamic)
  const componentMapOutput = `"use client"
// AUTO-GENERATED by scripts/scan-layouts.js — do not edit manually
import dynamic from 'next/dynamic'
import type { ComponentType } from 'react'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const componentMap: Record<string, ComponentType<any>> = {
${importEntries.join(',\n')}
}
`

  const componentMapFile = path.join(LAYOUTS_DIR, '_component-map.ts')
  fs.writeFileSync(componentMapFile, componentMapOutput, 'utf-8')
  console.log(`[scan-layouts] Found ${folders.length} layout(s): ${folders.join(', ')}`)
}

scanLayouts()
