// AUTO-GENERATED by scripts/scan-plugins.js — do not edit manually

export interface PluginHeaderMenu {
  label: string
  icon: string
  sortOrder: number
}

export interface PluginWidgetMeta {
  widgetKey: string
  title: string
  defaultZone: string
  defaultColSpan: number
  defaultRowSpan: number
  settingsSchema: Record<string, unknown> | null
}

export interface PluginAdminMenuItem {
  label: string
  icon: string
  path?: string
  isGroup?: boolean
  children?: PluginAdminMenuItem[]
}

export interface PluginMeta {
  name: string
  slug: string
  version: string
  author: string
  authorDomain: string
  repository: string
  description: string
  defaultEnabled: boolean
  hasRoutes: boolean
  hasApi: boolean
  hasAdmin: boolean
  hasWidgets: boolean
  hasMenus: boolean
  hasSchema: boolean
  headerMenus: PluginHeaderMenu[]
  widgetMetas: PluginWidgetMeta[]
  adminMenus: PluginAdminMenuItem[]
}

export const pluginManifest: Record<string, PluginMeta> = {
  'auction': {
    name: '경매',
    slug: 'auction',
    version: '1.0.0',
    author: 'kagla',
    authorDomain: 'https://kagla.com',
    repository: '',
    description: '실시간 경매 시스템',
    defaultEnabled: false,
    hasRoutes: true,
    hasApi: true,
    hasAdmin: true,
    hasWidgets: true,
    hasMenus: true,
    hasSchema: true,
    headerMenus: [{"label":"경매","icon":"🔨","sortOrder":3}],
    widgetMetas: [{"widgetKey":"auction-auction-live","title":"진행중 경매","defaultZone":"main","defaultColSpan":2,"defaultRowSpan":1,"settingsSchema":{"limit":4}}],
    adminMenus: [{"label":"경매관리","icon":"Gavel","path":"/admin/auction"}],
  },
  'boards': {
    name: '게시판',
    slug: 'boards',
    version: '1.0.0',
    author: 'kagla',
    authorDomain: 'https://kagla.com',
    repository: '',
    description: '커뮤니티 게시판 시스템',
    defaultEnabled: true,
    hasRoutes: true,
    hasApi: true,
    hasAdmin: true,
    hasWidgets: true,
    hasMenus: true,
    hasSchema: true,
    headerMenus: [{"label":"전체게시판","icon":"","sortOrder":10}],
    widgetMetas: [{"widgetKey":"boards-board-cards","title":"게시판 카드","defaultZone":"bottom","defaultColSpan":4,"defaultRowSpan":1,"settingsSchema":{"limit":4}},{"widgetKey":"boards-latest-posts","title":"최근 게시글","defaultZone":"main","defaultColSpan":2,"defaultRowSpan":2,"settingsSchema":{"limit":6}},{"widgetKey":"boards-popular-boards","title":"인기 게시판","defaultZone":"sidebar","defaultColSpan":1,"defaultRowSpan":2,"settingsSchema":{"limit":5}}],
    adminMenus: [{"label":"게시판관리","icon":"MessageSquare","path":"/admin/boards"}],
  },
  'contents': {
    name: '콘텐츠',
    slug: 'contents',
    version: '1.0.0',
    author: 'kagla',
    authorDomain: 'https://kagla.com',
    repository: '',
    description: '소개 페이지 관리 (회사소개, FAQ, 문의하기 등)',
    defaultEnabled: true,
    hasRoutes: true,
    hasApi: false,
    hasAdmin: true,
    hasWidgets: false,
    hasMenus: false,
    hasSchema: true,
    headerMenus: [],
    widgetMetas: [],
    adminMenus: [{"label":"콘텐츠관리","icon":"FileText","path":"/admin/contents"}],
  },
  'policies': {
    name: '약관',
    slug: 'policies',
    version: '1.0.0',
    author: 'kagla',
    authorDomain: 'https://kagla.com',
    repository: '',
    description: '이용약관, 개인정보처리방침 등 정책 페이지 관리',
    defaultEnabled: true,
    hasRoutes: true,
    hasApi: false,
    hasAdmin: true,
    hasWidgets: false,
    hasMenus: false,
    hasSchema: true,
    headerMenus: [],
    widgetMetas: [],
    adminMenus: [{"label":"약관관리","icon":"ScrollText","path":"/admin/policies"}],
  },
  'sample': {
    name: '샘플 플러그인',
    slug: 'sample',
    version: '0.1.0',
    author: 'kagla',
    authorDomain: 'https://kagla.com',
    repository: '',
    description: '플러그인 시스템 테스트용',
    defaultEnabled: true,
    hasRoutes: true,
    hasApi: true,
    hasAdmin: false,
    hasWidgets: false,
    hasMenus: false,
    hasSchema: false,
    headerMenus: [],
    widgetMetas: [],
    adminMenus: [],
  },
  'shop': {
    name: '쇼핑몰',
    slug: 'shop',
    version: '1.0.0',
    author: 'kagla',
    authorDomain: 'https://kagla.com',
    repository: '',
    description: '상품 판매, 주문, 결제 시스템',
    defaultEnabled: false,
    hasRoutes: true,
    hasApi: true,
    hasAdmin: true,
    hasWidgets: true,
    hasMenus: true,
    hasSchema: true,
    headerMenus: [{"label":"쇼핑","icon":"🛒","sortOrder":2}],
    widgetMetas: [{"widgetKey":"shop-shop-shortcut","title":"쇼핑몰 바로가기","defaultZone":"main","defaultColSpan":1,"defaultRowSpan":1,"settingsSchema":null}],
    adminMenus: [{"label":"쇼핑몰","icon":"ShoppingBag","isGroup":true,"children":[{"label":"대시보드","icon":"BarChart3","path":"/admin/shop"},{"label":"상품관리","icon":"Package","path":"/admin/shop/products"},{"label":"카테고리","icon":"ShoppingBag","path":"/admin/shop/categories"},{"label":"주문관리","icon":"ClipboardList","path":"/admin/shop/orders"},{"label":"매출관리","icon":"TrendingUp","path":"/admin/shop/sales"},{"label":"리뷰관리","icon":"Star","path":"/admin/shop/reviews"},{"label":"Q&A관리","icon":"MessageSquare","path":"/admin/shop/qna"},{"label":"배송비정책","icon":"Truck","path":"/admin/shop/delivery"},{"label":"쇼핑몰설정","icon":"Settings","path":"/admin/shop/settings"}]}],
  }
}

export type PluginFolder = keyof typeof pluginManifest
