// AUTO-GENERATED by scripts/scan-plugins.js — do not edit manually

export interface PluginMeta {
  name: string
  slug: string
  version: string
  author: string
  authorDomain: string
  repository: string
  description: string
  defaultEnabled: boolean
  hasRoutes: boolean
  hasApi: boolean
  hasAdmin: boolean
  hasWidgets: boolean
  hasMenus: boolean
  hasSchema: boolean
}

export const pluginManifest: Record<string, PluginMeta> = {
  'contents': {
    name: '콘텐츠',
    slug: 'contents',
    version: '1.0.0',
    author: 'kagla',
    authorDomain: 'https://kagla.com',
    repository: '',
    description: '소개 페이지 관리 (회사소개, FAQ, 문의하기 등)',
    defaultEnabled: true,
    hasRoutes: true,
    hasApi: false,
    hasAdmin: true,
    hasWidgets: false,
    hasMenus: false,
    hasSchema: false,
  },
  'sample': {
    name: '샘플 플러그인',
    slug: 'sample',
    version: '0.1.0',
    author: 'kagla',
    authorDomain: 'https://kagla.com',
    repository: '',
    description: '플러그인 시스템 테스트용',
    defaultEnabled: true,
    hasRoutes: true,
    hasApi: true,
    hasAdmin: false,
    hasWidgets: false,
    hasMenus: false,
    hasSchema: false,
  }
}

export type PluginFolder = keyof typeof pluginManifest
