// AUTO-GENERATED by scripts/scan-plugins.js — do not edit manually

export interface PluginMeta {
  name: string
  slug: string
  version: string
  author: string
  authorDomain: string
  repository: string
  description: string
  defaultEnabled: boolean
  hasRoutes: boolean
  hasApi: boolean
  hasAdmin: boolean
  hasWidgets: boolean
  hasMenus: boolean
  hasSchema: boolean
}

export const pluginManifest: Record<string, PluginMeta> = {
  'auction': {
    name: '경매',
    slug: 'auction',
    version: '1.0.0',
    author: 'kagla',
    authorDomain: 'https://kagla.com',
    repository: '',
    description: '실시간 경매 시스템',
    defaultEnabled: false,
    hasRoutes: true,
    hasApi: true,
    hasAdmin: true,
    hasWidgets: true,
    hasMenus: false,
    hasSchema: false,
  },
  'boards': {
    name: '게시판',
    slug: 'boards',
    version: '1.0.0',
    author: 'kagla',
    authorDomain: 'https://kagla.com',
    repository: '',
    description: '커뮤니티 게시판 시스템',
    defaultEnabled: true,
    hasRoutes: true,
    hasApi: true,
    hasAdmin: true,
    hasWidgets: false,
    hasMenus: false,
    hasSchema: false,
  },
  'contents': {
    name: '콘텐츠',
    slug: 'contents',
    version: '1.0.0',
    author: 'kagla',
    authorDomain: 'https://kagla.com',
    repository: '',
    description: '소개 페이지 관리 (회사소개, FAQ, 문의하기 등)',
    defaultEnabled: true,
    hasRoutes: true,
    hasApi: false,
    hasAdmin: true,
    hasWidgets: false,
    hasMenus: false,
    hasSchema: false,
  },
  'policies': {
    name: '약관',
    slug: 'policies',
    version: '1.0.0',
    author: 'kagla',
    authorDomain: 'https://kagla.com',
    repository: '',
    description: '이용약관, 개인정보처리방침 등 정책 페이지 관리',
    defaultEnabled: true,
    hasRoutes: true,
    hasApi: false,
    hasAdmin: true,
    hasWidgets: false,
    hasMenus: false,
    hasSchema: false,
  },
  'sample': {
    name: '샘플 플러그인',
    slug: 'sample',
    version: '0.1.0',
    author: 'kagla',
    authorDomain: 'https://kagla.com',
    repository: '',
    description: '플러그인 시스템 테스트용',
    defaultEnabled: true,
    hasRoutes: true,
    hasApi: true,
    hasAdmin: false,
    hasWidgets: false,
    hasMenus: false,
    hasSchema: false,
  },
  'shop': {
    name: '쇼핑몰',
    slug: 'shop',
    version: '1.0.0',
    author: 'kagla',
    authorDomain: 'https://kagla.com',
    repository: '',
    description: '상품 판매, 주문, 결제 시스템',
    defaultEnabled: false,
    hasRoutes: true,
    hasApi: true,
    hasAdmin: true,
    hasWidgets: false,
    hasMenus: false,
    hasSchema: false,
  }
}

export type PluginFolder = keyof typeof pluginManifest
