"use client"
// AUTO-GENERATED by scripts/scan-layouts.js — do not edit manually
import dynamic from 'next/dynamic'
import type { ComponentType } from 'react'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const componentMap: Record<string, ComponentType<any>> = {
  'default/Header': dynamic(() => import('@/layouts/default/Header')),
  'default/HomePage': dynamic(() => import('@/layouts/default/HomePage')),
  'default/Footer': dynamic(() => import('@/layouts/default/Footer'))
}
