// AUTO-GENERATED by scripts/scan-layouts.js — do not edit manually

export const layoutManifest = {
  "default": {
    "name": "default",
    "files": {
      "Header": true,
      "HomePage": true,
      "Footer": true
    }
  }
} as const

export type LayoutFolder = keyof typeof layoutManifest
export type LayoutComponent = 'Header' | 'HomePage' | 'Footer'
